global:
  scrape_interval: 15s # Waktu pengambilan data setiap 15 detik

scrape_configs:
  - job_name: 'ml_model_monitoring'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Port metrik dari python
